# Generated by Django 5.2.3 on 2025-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_img',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_img'),
        ),
    ]
