# Generated by Django 5.2.3 on 2025-07-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemonentity_next_evolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='next_evolution',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='previous_evolution',
        ),
    ]
